- hosts: "{{ lookup('env','HOST_GROUP') }}"
  remote_user: devops
  vars:
    HOSTNAME: "http://localhost:8080"
  tasks:
    - name: GET '/api/user'
      uri:
        url: ${HOSTNAME}/api/user
        method: GET
        status_code: 200

    - name: GET '/api/tags'
      uri:
        url: ${HOSTNAME}/api/tags
        method: GET
        status_code: 200

    - name: GET '/api/articles'
      uri:
        url: ${HOSTNAME}/api/articles
        method: GET
        status_code: 200