- hosts: "{{ lookup('env','HOST_GROUP') }}"
  remote_user: devops
  vars:
    HOST_NAME: "http://localhost:8080"
  tasks:
    - name: GET '/api/user'
      uri:
        url: "{{ HOST_NAME }}/api/user"
        method: GET
        status_code: 200

    - name: GET '/api/tags'
      uri:
        url: "{{ HOST_NAME }}/api/tags"
        method: GET
        status_code: 200

    - name: GET '/api/articles'
      uri:
        url: "{{ HOST_NAME }}/api/articles"
        method: GET
        status_code: 200